name: publish

on:
  push:
    tags:
      - 'v*'

jobs:
  gleam_build:
    runs-on: docker-cli
    container:
      image: ghcr.io/gleam-lang/gleam:v1.12.0-node-alpine
    steps:
      - name: Add git
        run: apk add git
      - name: Checkout repository
        run: git clone --branch ${{ forge.ref_name }} ${{ forge.server_url }}/${{ forge.repository }}.git

      - name: Run gleam build
        run: cd condition_overload && gleam build

      - name: Display build artifacts
        run: ls ./condition_overload/build/dev/javascript/

      - name: Upload artifacts
        uses: https://code.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: gleam_build.zip
          path: ./condition_overload/build/dev/javascript/
          if-no-files-found: error 

  bun_package:
    needs: gleam_build
    runs-on: docker-cli
    container:
      image: oven/bun:latest
    steps:
      - name: apt update & apt install zip
        run: |
          apt update -y
          apt install zip -y

      - name: Download artifact
        uses: https://code.forgejo.org/forgejo/download-artifact@v4
        with:
          name: gleam_build.zip
          path: ./build

      - name: Build linux-x64
        run: bun build --compile --target=bun-linux-x64 ./build/condition_overload/entry.mjs --outfile ./build/bin/linux-x64/condition_overload

      - name: Build linux-arm64
        run: bun build --compile --target=bun-linux-arm64 ./build/condition_overload/entry.mjs --outfile ./build/bin/linux-arm64/condition_overload

      - name: Build windows-x64
        run: bun build --compile --target=bun-windows-x64 ./build/condition_overload/entry.mjs --outfile ./build/bin/windows-x64/condition_overload

      - name: Build darwin-x64
        run: bun build --compile --target=bun-darwin-x64 ./build/condition_overload/entry.mjs --outfile ./build/bin/darwin-x64/condition_overload

      - name: Build darwin-arm64
        run: bun build --compile --target=bun-darwin-arm64 ./build/condition_overload/entry.mjs --outfile ./build/bin/darwin-arm64/condition_overload

      - name: Build x64-musl
        run: bun build --compile --target=bun-x64-musl ./build/condition_overload/entry.mjs --outfile ./build/bin/x64-musl/condition_overload

      - name: Build linux-arm64-musl
        run: bun build --compile --target=bun-linux-arm64-musl ./build/condition_overload/entry.mjs --outfile ./build/bin/linux-arm64-musl/condition_overload

      - name: Zip binaries
        run: |
          for dir in ./build/bin/*/; do 
              dir=${dir%*/}
              
              zip -r "${dir}.zip" "${dir}/" -j
              rm $dir -rf
          done

      - name: Upload release
        uses: https://data.forgejo.org/actions/forgejo-release@v2.7.1
        with: 
          direction: upload
          url: "https://git.nuv.sh"
          repo: "nuv/condition_overload"
          token: ${{ secrets.TOKEN }}
          tag: ${{ forge.ref_name }}
          override: true
          release-dir: ./build/bin/
          release-notes: ${{ env.FORGEJO_SHA }}
